version: "3"
services:
  app:
    container_name: paige_app
    build: .
    volumes:
      - .:/app/
    ports:
      - "8080:8080"
    depends_on:
      - phantomjs
      - postgres
    environment:
      NODE_ENV: development
      PORT: 8080
      WEBDRIVER_HOST: phantomjs
      WEBDRIVER_PORT: 8910
      DATABASE_URL: postgres://user@postgres:5432/example
      APP_SECRET: 12345abcde
      MAILGUN_EMAIL: <MAILGUN_EMAIL e.g. postmaster@sandbox.mailgun.org>
      MAILGUN_DOMAIN: <MAILGUN_DOMAIN e.g. sandbox.mailgun.org>
      MAILGUN_ACTIVE_API_KEY: <MAILGUN_ACTIVE_API_KEY>
      RESET_PASSWORD_URL: http://localhost:8080/reset-password?token=
      LOGIN_URL: http://localhost:8080/login
      CONFIRM_EMAIL_URL: http://localhost:8080/confirm-email?token=
  phantomjs:
    container_name: "paige_phantomjs"
    image: wernight/phantomjs:2.1.1
    ports:
      - "8910:8910"
    command: "phantomjs --webdriver=8910 --ignore-ssl-errors=true --ssl-protocol=any"
  postgres:
    container_name: paige_postgres
    image: postgres:9.6.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: example